enableStrictSsl: true

enableTelemetry: 0

networkSettings:
  registry.npmjs.org:
    enableNetwork: true
  registry.yarnpkg.com:
    enableNetwork: true

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.5.0.cjs
