#!/bin/bash
# Copyright (C) NIWA & British Crown (Met Office) & Contributors.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

if ! sed --version 2>/dev/null | grep -q 'GNU' 2>/dev/null; then
    echo -e '** GNU sed required **\n' >&2
    exit 1
fi

cd "$(dirname "$0")" || exit 1
CHECK_FILE='checkpoint.js'

# Using cylc install results in get_checkpoint.py not being found by the
# task. We can either copy it when installing
cylc install --no-run-name --flow-name="one" --directory=one
# ln -s "${PWD}/one/" "${HOME}/cylc-run/one"

if cylc play "one" --fcp=20000102T0000Z --no-detach; then
    cp \
        "${HOME}/cylc-run/one/work/20000102T0000Z/checkpoint/checkpoint" \
        "${CHECK_FILE}"
    rm -r "${HOME}/cylc-run/one"
else
    echo -e '** Suite run failed **\n' >&2
    exit 1
fi

sed -i \
    -e "1s|^|const checkpoint = |" \
    -e "1s|^|/* eslint-disable */\n|" \
    -e "s|$USER|user|g" \
    -e "s|$(hostname)|localhost|g" \
    -e "s|$(hostname | tr '[:upper:]' '[:lower:]')|localhost|g" \
    -e "\$s|$|\nexport { checkpoint }|" \
    "${CHECK_FILE}"
