#!/bin/bash

if ! sed --version 2>/dev/null | grep -q 'GNU' 2>/dev/null; then
    echo -e '** GNU sed required **\n' >&2
    exit 1
fi

cd "$(dirname "$0")" || exit 1
CHECK_FILE='checkpoint.js'

cylc reg "one" one
if cylc run "one" --fcp=20000102T0000Z --no-detach; then
    cp \
        "${HOME}/cylc-run/one/work/20000102T0000Z/checkpoint/checkpoint" \
        "${CHECK_FILE}"
    rm -r "${HOME}/cylc-run/one"
else
    echo -e '** Suite run failed **\n' >&2
    exit 1
fi

sed -i \
    -e "1s|^|const checkpoint = |" \
    -e "1s|^|/* eslint-disable */\n|" \
    -e "s|$USER|user|g" \
    -e "s|$(hostname)|localhost|g" \
    -e "s|$(hostname | tr '[:upper:]' '[:lower:]')|localhost|g" \
    -e "\$s|$|\nexport { checkpoint }|" \
    "${CHECK_FILE}"
