#!/bin/bash


CHECK_FILE='checkpoint.js'


cylc reg "one" one


if cylc run "one" --fcp=20000102T0000Z --no-detach; then
    cp \
        "${HOME}/cylc-run/one/work/20000102T0000Z/checkpoint/checkpoint" \
        "${CHECK_FILE}"
    rm -r "${HOME}/cylc-run/one"
else
    exit 1
fi

sed -i "1 s/^/const checkpoint=/; s/${USER}/cylc/g" "${CHECK_FILE}"
echo -e '\nexport { checkpoint }' >> "${CHECK_FILE}"
