name: Validate Renovate config

on:
  pull_request:
    paths:
      - renovate.json
      - '.github/workflows/renovate_validate.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 2

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 'lts/*'

      - name: Validate config
        run: npx --yes --package renovate -- renovate-config-validator
